# Generated by Django 2.2.6 on 2019-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=254)),
                ('name_displayed', models.CharField(max_length=100)),
                ('item_slug', models.CharField(max_length=254)),
            ],
        ),
    ]
