# Generated by Django 2.2.6 on 2019-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdflist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='item_slug',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
