# Generated by Django 2.2.6 on 2019-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdflist', '0002_auto_20191004_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='item_slug',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
